#!/bin/bash
# Per-server .bashrc management: static block injection and fleetman.sh generation.
# Sourced by sync.sh and install.sh for local operations only.
# Remote operations use equivalent heredoc logic (no lib access on remote).
# Pure utilities — callers are responsible for emitting ok/err/warn messages.
[[ -n "${_FLEETMAN_BASHRC_LOADED:-}" ]] && return 0
_FLEETMAN_BASHRC_LOADED=1

_LIB_BASHRC="$(dirname "${BASH_SOURCE[0]}")"
# shellcheck source=scripts/lib/vars.sh
source "$_LIB_BASHRC/vars.sh"
# shellcheck source=scripts/lib/display.sh
source "$_LIB_BASHRC/display.sh"

# Appends the static BEGIN/END FLEETMAN sourcing block to $HOME/.bashrc if absent.
# Idempotent. Returns 0 if block was added, 1 if already present.
write_fleetman_bashrc_block() {
    if ! grep -qF '# BEGIN FLEETMAN' "$HOME/.bashrc" 2>/dev/null; then
        {
            echo ""
            echo "# BEGIN FLEETMAN"
            # shellcheck disable=SC2016
            echo '[[ -f ~/.data/fleetman.sh ]] && . ~/.data/fleetman.sh'
            echo "# END FLEETMAN"
        } >> "$HOME/.bashrc"
        return 0
    fi
    return 1
}

# Generates $DATA_DIR/fleetman.sh from $CONFIG_FILE.
# Fully overwrites on each call. Caller must ensure CONFIG_FILE is present.
# Uses literal variable references (e.g. $HOME) — expanded at login, not at generation time.
generate_fleetman_sh() {
    local _welcome_enabled
    _welcome_enabled=$(jq -r 'if .welcome.enabled == false then "false" else "true" end' \
        "$CONFIG_FILE" 2>/dev/null)
    _welcome_enabled="${_welcome_enabled:-true}"

    local _base_folder
    _base_folder=$(jq -r '.base_folder // ""' "$CONFIG_FILE" 2>/dev/null)

    mkdir -p "$DATA_DIR"
    {
        echo "# Generated by fleetman — do not edit manually"
        # shellcheck disable=SC2016
        echo 'export PATH="$HOME/scripts/bin:$PATH"'
        echo 'if [ -f ~/.bash_aliases ]; then . ~/.bash_aliases; fi'
        echo 'if [ -f ~/scripts/internal/completion.sh ]; then . ~/scripts/internal/completion.sh; fi'
        if [ "$_welcome_enabled" = "true" ]; then
            # shellcheck disable=SC2016
            echo '[[ $SHLVL -eq 1 && -t 1 && -f ~/scripts/internal/welcome.sh ]] && ~/scripts/internal/welcome.sh'
        fi
        if [ -n "$_base_folder" ]; then
            echo "[[ \$SHLVL -eq 1 && -d $_base_folder ]] && cd $_base_folder"
        fi
    } > "$DATA_DIR/fleetman.sh"
}
