#!/bin/bash

# Welcome screen displayed on SSH login.
# Called from .bashrc only for interactive login shells (SHLVL=1, stdout is a TTY).
# ASCII art is pre-generated by fleetman sync and stored in ~/.data/welcome_<host>.ascii.

_LIB="$(dirname "${BASH_SOURCE[0]}")/../lib"
# shellcheck source=scripts/lib/vars.sh
source "$_LIB/vars.sh"
# shellcheck source=scripts/lib/display.sh
source "$_LIB/display.sh"

# ── Layout constants ───────────────────────────────────────────────────────────

BOX_W=80      # total inner width (between the two │)
LEFT_W=38     # left column visible width (incl. leading space, excl. right │)
RIGHT_W=$(( BOX_W - LEFT_W - 1 ))  # 41

# ── Drawing helpers ────────────────────────────────────────────────────────────

# Remove ANSI escape codes and measure visible length.
# Pure-bash: no fork (~0ms vs ~7ms for printf|sed|wc per call).
# ${#_s} counts characters (not bytes) when locale is UTF-8 — correct for braille art.
visible_len() {
    local _s
    shopt -s extglob
    _s="${1//$'\e'\[+([0-9;])m/}"
    echo "${#_s}"
}

# Pad a string (which may contain ANSI codes) to a given visible width
pad_right() {
    local str="$1" width="$2"
    local vlen
    vlen=$(visible_len "$str")
    local pad=$(( width - vlen ))
    if [ "$pad" -gt 0 ]; then
        printf '%s%*s' "$str" "$pad" ''
    else
        printf '%s' "$str"
    fi
}

# 10-char progress bar: filled part in env colour, empty in dark grey
# shellcheck disable=SC2059
make_bar() {
    local pct=$1
    local filled=$(( pct * 10 / 100 ))
    local empty=$(( 10 - filled ))
    local bar="" i
    local color
    if (( pct < 50 )); then
        color="$GREEN"
    elif (( pct < 75 )); then
        color="$YELLOW"
    else
        color="$RED"
    fi
    if [ "$filled" -gt 0 ]; then
        bar=""; for (( i=0; i<filled; i++ )); do bar+='█'; done
        printf "%b%s%b" "$color" "$bar" "$NC"
    fi
    if [ "$empty" -gt 0 ]; then
        bar=""; for (( i=0; i<empty; i++ )); do bar+='█'; done
        printf "%b%s%b" "$GREY" "$bar" "$NC"
    fi
}

# Horizontal line of ─ repeated N times
hline() { local i; for (( i=0; i<$1; i++ )); do printf '─'; done; }

# Full-width box row (content spans the full inner width)
box_full() {
    printf "│ %s │\n" "$(pad_right "$1" $(( BOX_W - 2 )))"
}

# Two-column box row
box_two() {
    printf "│ %s│ %s│\n" \
        "$(pad_right "$1" $(( LEFT_W - 1 )))" \
        "$(pad_right "$2" $(( RIGHT_W - 1 )))"
}

# ── Data collection ────────────────────────────────────────────────────────────

_SHOW_WELCOME="true"
_SHOW_PODS="true"
_SHOW_OS="true"
_SHOW_DOCKER="true"

load_welcome_config() {
    if [ ! -f "$CONFIG_FILE" ]; then return 0; fi
    local cfg
    cfg=$(jq -r '[
        (if .welcome.enabled    == false then "false" else "true" end),
        (if .welcome.show_pods  == false then "false" else "true" end),
        (if .welcome.show_os    == false then "false" else "true" end),
        (if .welcome.show_docker == false then "false" else "true" end)
    ] | join(" ")' "$CONFIG_FILE" 2>/dev/null) || true
    read -r _SHOW_WELCOME _SHOW_PODS _SHOW_OS _SHOW_DOCKER <<< "${cfg:-true true true true}"
}

resolve_env() {
    ENV_NAME=$(jq -r --arg h "$FQDN" \
        '.servers | to_entries[] | select(.value[] == $h) | .key' \
        "$CONFIG_FILE" 2>/dev/null)

    ENV_COLOR_NAME=$(jq -r --arg e "$ENV_NAME" '.env_colors[$e] // "white"' "$CONFIG_FILE" 2>/dev/null)

    ENV_FG=$(env_color_ansi "$ENV_COLOR_NAME" fg)
    ENV_BG=$(env_color_ansi "$ENV_COLOR_NAME" bg)
}

collect_system_info() {
    local loadavg_file="${_LOADAVG_FILE:-/proc/loadavg}"
    local osrelease_file="${_OSRELEASE_FILE:-/etc/os-release}"

    OS=$(. "$osrelease_file" 2>/dev/null && echo "$PRETTY_NAME")
    KERNEL=$(uname -r)
    LOAD=$(awk '{print $1" / "$2" / "$3}' "$loadavg_file")
    LOAD1=$(awk '{print $1}' "$loadavg_file")
    NCPU=$(nproc 2>/dev/null || echo 1)
    LOAD_PCT=$(awk "BEGIN{v=$LOAD1*100/$NCPU; printf \"%d\", (v>100?100:v)}")
    RAM_TOTAL=$(free -m 2>/dev/null | awk '/^Mem:/{print $2}')
    RAM_USED=$(free -m  2>/dev/null | awk '/^Mem:/{print $3}')
    RAM_TOTAL_H=$(free -h 2>/dev/null | awk '/^Mem:/{print $2}')
    RAM_USED_H=$(free -h  2>/dev/null | awk '/^Mem:/{print $3}')
    RAM_PCT=$(( RAM_TOTAL > 0 ? RAM_USED * 100 / RAM_TOTAL : 0 ))
    UPTIME=$(uptime -p 2>/dev/null | sed 's/^up //' | sed 's/\([^,]*,[^,]*,[^,]*\),.*/\1/' || uptime | sed 's/.*up //' | cut -d, -f1)
    LAST_SYNC=""
    if [ -f "$DATA_DIR/last_sync.txt" ]; then
        LAST_SYNC=$(< "$DATA_DIR/last_sync.txt")
    fi
}

collect_pods() {
    mapfile -t PODS < <(
        jq -r --arg e "$ENV_NAME" --arg h "$FQDN" \
            '.[$e][$h][]? // empty' "$PODS_FILE" 2>/dev/null
    )
}

# ── Container status ───────────────────────────────────────────────────────────

_run_docker() {
    if [ -n "$_DOCKER_PASS" ]; then
        echo "$_DOCKER_PASS" | timeout 3 sudo -S docker "$@" 2>/dev/null
    else
        timeout 3 docker "$@" 2>/dev/null
    fi
}

collect_container_status() {
    _DOCKER_PASS=""
    if [ -f "$FLEET_KEY" ] && [ -f "$FLEET_PASS_FILE" ]; then
        _DOCKER_PASS=$(timeout 2 openssl pkeyutl -decrypt -inkey "$FLEET_KEY" \
            -pkeyopt rsa_padding_mode:oaep < "$FLEET_PASS_FILE" 2>/dev/null) || true
    fi

    WUD_PORT=$(jq -r '.status_checks.wud_port // empty' "$CONFIG_FILE" 2>/dev/null)

    container_rows=()
    # Single docker ps call — avoids slow docker info + N×docker inspect
    local ps_output
    if ps_output=$(_run_docker ps --all --format '{{.Names}}|{{.State}}'); then
        container_rows+=("$(printf "%b" "${BLUE}Docker${NC} ${GREEN}✓${NC}")")

        local wud_json=""
        if [ -n "$WUD_PORT" ]; then
            wud_json=$(curl -sf --max-time 2 "http://localhost:${WUD_PORT}/api/containers" 2>/dev/null) || true
        fi

        # Build name→state map from ps output
        declare -A _cstatus_map
        while IFS='|' read -r _cn _cs; do
            [ -n "$_cn" ] && _cstatus_map["$_cn"]="$_cs"
        done <<< "$ps_output"

        local cname cstatus update_flag has_update
        while IFS= read -r cname; do
            [ -z "$cname" ] && continue
            cstatus="${_cstatus_map[$cname]:-}"
            if [ "$cstatus" = "running" ]; then
                update_flag=""
                if [ -n "$wud_json" ]; then
                    has_update=$(printf '%s' "$wud_json" | jq -r --arg n "$cname" \
                        '[.[] | select(.name == $n and .updateAvailable == true)] | length' 2>/dev/null) || true
                    [ "$has_update" != "0" ] && [ -n "$has_update" ] && \
                        update_flag=" $(printf "%b" "${YELLOW}⬆${NC}")"
                fi

                container_rows+=("$(printf "  · ${NC}%s${NC} ${GREEN}✓${NC}%s" "$cname" "$update_flag")")
            elif [ -n "$cstatus" ]; then
                container_rows+=("$(printf "  · ${NC}%s${NC} ${YELLOW}⚠ ${NC}%s" "$cname" "$cstatus")")
            else
                container_rows+=("$(printf "  · ${NC}%s${NC} ${RED}✗${NC}" "$cname")")
            fi
        done < <(jq -r '.status_checks.containers // [] | .[]' "$CONFIG_FILE" 2>/dev/null)
    else
        container_rows+=("$(printf "%b" "${BLUE}Docker${NC} ${RED}✗ not running${NC}")")
    fi
}

# ── ASCII art ──────────────────────────────────────────────────────────────────

load_ascii_art() {
    local ascii_file="$DATA_DIR/welcome_${HOST}.ascii"
    ASCII_LINES=()
    if [ -f "$ascii_file" ]; then
        mapfile -t ASCII_LINES < "$ascii_file"
    fi
}

# ── Render ─────────────────────────────────────────────────────────────────────

# shellcheck disable=SC2059
render() {
    # Top border
    printf "┌%s┐\n" "$(hline $BOX_W)"

    # Header: ◉ (always green) + short hostname   [ENV] right-aligned
    local header_left header_env env_len name_len gap header_line
    header_left=$(printf "${GREEN} \xe2\x97\x89 ${NC} %s" "$HOST")   # ◉ always green
    header_env=$(printf "${ENV_FG}[ %s ]${NC}" "${ENV_NAME^^}")
    env_len=$(visible_len "$header_env")
    name_len=$(visible_len "$header_left")
    gap=$(( BOX_W - 2 - name_len - env_len ))
    header_line="${header_left}$(printf '%*s' $gap '')${header_env}"
    box_full "$header_line"

    # Braille ASCII art (2 lines, full-width coloured background)
    if [ "${#ASCII_LINES[@]}" -ge 2 ]; then
        box_full "$(printf "${ENV_BG}%s${NC}" "$(pad_right "${ASCII_LINES[0]}" $(( BOX_W - 2 )))")"
        box_full "$(printf "${ENV_BG}%s${NC}" "$(pad_right "${ASCII_LINES[1]}" $(( BOX_W - 2 )))")"
    else
        box_full ""
        box_full ""
    fi

    # Build left column conditionally
    local -a left_rows=()
    if [ "$_SHOW_OS" = "true" ]; then
        left_rows+=(
            "$(printf "${BLUE}OS${NC}     %s" "$OS")"
            "$(printf "${BLUE}Kernel${NC} %s" "$KERNEL")"
            "$(printf "${BLUE}Load${NC}   %s %s" "$(make_bar "$LOAD_PCT")" "$LOAD")"
            "$(printf "${BLUE}RAM${NC}    %s %s/%s" "$(make_bar "$RAM_PCT")" "$RAM_USED_H" "$RAM_TOTAL_H")"
            "$(printf "${BLUE}Uptime${NC} %s" "$UPTIME")"
            "$(printf "${BLUE}Sync${NC}   %s" "${LAST_SYNC:-(never)}")"
        )
    fi
    if [ "$_SHOW_DOCKER" = "true" ] && [ "${#container_rows[@]}" -gt 0 ]; then
        if [ "${#left_rows[@]}" -gt 0 ]; then
            left_rows+=("")
        fi
        left_rows+=("${container_rows[@]}")
    fi

    # Build right column conditionally
    local -a right_rows=()
    if [ "$_SHOW_PODS" = "true" ]; then
        right_rows+=("$(printf "%b%s%b" "${BLUE}" "Pods$" "${NC}")")
        if [ "${#PODS[@]}" -eq 0 ]; then
            right_rows+=("  (none)")
        else
            local pod
            for pod in "${PODS[@]}"; do
                right_rows+=("  ·  $pod")
            done
        fi
    fi

    # Layout decision
    local show_left show_right
    if [ "${#left_rows[@]}" -gt 0 ]; then show_left="true"; else show_left="false"; fi
    if [ "${#right_rows[@]}" -gt 0 ]; then show_right="true"; else show_right="false"; fi

    local max_rows i row
    if [ "$show_left" = "true" ] && [ "$show_right" = "true" ]; then
        # Two-column layout
        printf "├%s┬%s┤\n" "$(hline $LEFT_W)" "$(hline $RIGHT_W)"
        max_rows=$(( ${#left_rows[@]} > ${#right_rows[@]} ? ${#left_rows[@]} : ${#right_rows[@]} ))
        for i in $(seq 0 $(( max_rows - 1 ))); do
            box_two "${left_rows[$i]:-}" "${right_rows[$i]:-}"
        done
        printf "└%s┴%s┘\n" "$(hline $LEFT_W)" "$(hline $RIGHT_W)"
    elif [ "$show_left" = "true" ]; then
        # Single-column: left content full-width
        printf "├%s┤\n" "$(hline $BOX_W)"
        for row in "${left_rows[@]}"; do
            box_full "$row"
        done
        printf "└%s┘\n" "$(hline $BOX_W)"
    elif [ "$show_right" = "true" ]; then
        # Single-column: right content (pods) full-width
        printf "├%s┤\n" "$(hline $BOX_W)"
        for row in "${right_rows[@]}"; do
            box_full "$row"
        done
        printf "└%s┘\n" "$(hline $BOX_W)"
    else
        # No body: header + bottom border only
        printf "└%s┘\n" "$(hline $BOX_W)"
    fi
}

# ── Main ───────────────────────────────────────────────────────────────────────

main() {
    [[ -t 1 ]] || return 0

    FQDN="$MASTER_HOST"          # set by vars.sh — avoids a second slow DNS call
    HOST="${FQDN%%.*}"           # short name: server3-dev.abc.example.com → server3-dev

    load_welcome_config
    [ "$_SHOW_WELCOME" = "false" ] && return 0

    # Start docker collection in background immediately (slow: openssl + docker ps)
    local _tmpdir="" _docker_pid=""
    if [ "$_SHOW_DOCKER" = "true" ]; then
        _tmpdir=$(mktemp -d)
        (
            collect_container_status
            # Atomic write: only visible once fully written
            declare -p container_rows > "$_tmpdir/container_rows.tmp" \
                && mv "$_tmpdir/container_rows.tmp" "$_tmpdir/container_rows"
        ) &
        _docker_pid=$!
    fi

    resolve_env
    collect_system_info
    collect_pods
    load_ascii_art

    # Check docker results opportunistically — no blocking wait.
    # Poll up to 600ms (6 × 100ms) for the background job to finish.
    # Foreground already took ~200ms, so total budget is ~800ms before giving up.
    if [ -n "$_docker_pid" ]; then
        local _i
        for _i in 1 2 3 4 5 6; do
            [ -f "$_tmpdir/container_rows" ] && break
            sleep 0.1
        done
        kill "$_docker_pid" 2>/dev/null || true
        container_rows=()
        if [ -f "$_tmpdir/container_rows" ]; then
            # shellcheck source=/dev/null
            source "$_tmpdir/container_rows"
        fi
        rm -rf "$_tmpdir"
    fi

    render
}

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then main "$@"; fi
